backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}: {{title}}'
    update: 'Update {{collection}}: {{title}}'
    delete: 'Delete {{collection}}: {{title}}'
    uploadMedia: '[skip ci] Upload: {{path}}'
    deleteMedia: '[skip ci] Delete: {{path}}'

local_backend: true

media_folder: static/images
public_folder: /images

collections:
  - name: 'states'
    label: 'States'
    label_singular: 'State'
    extension: 'md'
    media_folder: ''
    public_folder: ''
    folder: 'content/states'
    path: '{{title}}/index'
    create: true
    title: '{{title}}/index'
    preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        required: true

      - label: 'Redirect'
        name: 'redirect'
        widget: 'string'
        required: false
        hint: 'Old Tumblr URL. Will be hidden after migration.'

      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        required: true

      - label: 'Image'
        name: 'image'
        widget: image
        required: true

      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: true

      - label: 'Product'
        name: 'product'
        widget: 'string'
        required: false
        hint: 'What is the name of the app or product. This will be used to help find related states below.'

      - label: 'Related States'
        name: 'related'
        widget: 'relation'
        collection: 'states'
        searchFields: ['title', 'product']
        valueField: 'title'
        displayFields: ['product', 'title']
        required: false
        multiple: true

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false
